-- 코드를 입력하세요
# GENDER 0 -남자, 1 -여자
# 해결할 것 - 각 년월에 한 유저가 여러번 삿을수도 잇다! -> 이건 그냥 카운팅 1로 해줘야 함 DISTINCT해도 안먹혀
SELECT YEAR(SALES_DATE) AS YEAR, MONTH(SALES_DATE) AS MONTH, A.GENDER, COUNT(DISTINCT B.USER_ID) AS USERS
FROM USER_INFO A
JOIN ONLINE_SALE B
ON A.USER_ID = B.USER_ID
WHERE A.GENDER IS NOT NULL
GROUP BY YEAR, MONTH, GENDER
ORDER BY YEAR, MONTH, GENDER;