-- 코드를 입력하세요
# 우유와 요거트 동시에 구입한 장바구니 아이디 조회
# SELECT DISTINCT CART_ID
# FROM CART_PRODUCTS
# WHERE CART_ID IN 
# (
# SELECT *
# FROM CART_PRODUCTS
# WHERE NAME = 'Yogurt' or NAME = 'Milk'
# GROUP BY CART_ID
# HAVING COUNT(CART_ID) >= 2
# )
# ORDER BY CART_ID;

SELECT DISTINCT CART_ID
FROM CART_PRODUCTS
WHERE CART_ID IN (
    SELECT CART_ID
    FROM CART_PRODUCTS
    WHERE NAME = 'Yogurt'
) AND CART_ID IN (
    SELECT CART_ID
    FROM CART_PRODUCTS
    WHERE NAME = 'Milk'
)
ORDER BY CART_ID;