-- 코드를 입력하세요
# 입양 간 동물 중 -> ANIMAL_OUTS
# 보호기간이 가장 길었떤 동물 두 마리의 아이디/이름 -> LIMIT
SELECT A.ANIMAL_ID, A.NAME
FROM ANIMAL_INS A
JOIN ANIMAL_OUTS B
ON A.ANIMAL_ID = B.ANIMAL_ID
# WHERE DATEDIFF(B.DATETIME, A.DATETIME)
ORDER BY DATEDIFF(B.DATETIME, A.DATETIME) DESC
LIMIT 2;