# 2022/8 ~ 2022/10 까지 대여 횟수 5회 이상 자동차 -> 월별 자동차 ID별 총 대여횟수 RECORDS
# 긍까, 저 기간동안 5회 이상 빌린 것들만 추리고 -> 8/9/10월 각 달마다 빌린 횟수 체크
# 대여 횟수가 0이면 결과에서 제외 IS NOT NULL
-- 코드를 입력하세요
SELECT MONTH(START_DATE) AS MONTH, CAR_ID, COUNT(CAR_ID) AS RECORDS
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN ( # 해당 기간동안 대여횟수 5회 이상인 자동차ID
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY 
    WHERE START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
    GROUP BY CAR_ID
    HAVING COUNT(CAR_ID) >= 5
)
AND START_DATE BETWEEN '2022-08-01' AND '2022-10-31'
GROUP BY MONTH, CAR_ID
HAVING RECORDS > 0
ORDER BY MONTH ASC, CAR_ID DESC;