-- 코드를 입력하세요
SELECT 
USER_ID, 
NICKNAME, 
CONCAT(U.City, " ", U.Street_address1, " ", U.street_address2)AS '전체주소', 
CONCAT(LEFT(TLNO,3), "-", SUBSTRING(TLNO,4,4), "-", RIGHT(TLNO,4))AS '전화번호'
FROM USED_GOODS_BOARD B
JOIN USED_GOODS_USER U
ON B.WRITER_ID = U.USER_ID
GROUP BY B.WRITER_ID
HAVING COUNT(B.WRITER_ID) >= 3
ORDER BY U.USER_ID DESC;