-- 코드를 입력하세요
SELECT B.USER_ID, B.NICKNAME, 
CONCAT_WS(" ", B.CITY, B.STREET_ADDRESS1, B.STREET_ADDRESS2) AS '전체주소', 
CONCAT(LEFT(TLNO, 3), '-', SUBSTRING(TLNO, 4, 4), '-', RIGHT(TLNO, 4)) AS '전화번호'
FROM USED_GOODS_BOARD A
JOIN USED_GOODS_USER B
ON A.WRITER_ID = B.USER_ID
GROUP BY B.USER_ID
HAVING COUNT(B.USER_ID) >= 3
ORDER BY USER_ID DESC;

# SELECT 
#     U.USER_ID, 
#     U.NICKNAME, 
#     CONCAT_WS(" ", U.CITY, U.STREET_ADDRESS1, U.STREET_ADDRESS2) AS "전체주소", 
#     CONCAT_WS("-", SUBSTR(U.TLNO, 1, 3), SUBSTR(U.TLNO, 4, 4), SUBSTR(U.TLNO, 8, 4)) AS "전화번호"
# FROM USED_GOODS_BOARD B
# INNER JOIN USED_GOODS_USER U
#     ON B.WRITER_ID = U.USER_ID
# GROUP BY U.USER_ID
#     HAVING COUNT(U.USER_ID) >= 3 
# ORDER BY U.USER_ID DESC;