-- 코드를 입력하세요
# 가격이 제일 비싼 것
SELECT CATEGORY, MAX(PRICE) AS MAX_PRICE, PRODUCT_NAME
FROM FOOD_PRODUCT
WHERE CATEGORY IN ('과자', '국', '김치', '식용유') 
AND PRICE IN (
    SELECT MAX(PRICE) 
    FROM FOOD_PRODUCT
    GROUP BY CATEGORY
)
GROUP BY CATEGORY, PRODUCT_NAME
HAVING MAX(PRICE)
ORDER BY PRICE DESC;