-- 코드를 입력하세요
# 2022년 1월의 카테고리 별 도서 판매량을 합산

SELECT A.CATEGORY, SUM(B.SALES) AS TOTAL_SALES
FROM BOOK A
JOIN BOOK_SALES B
ON A.BOOK_ID = B.BOOK_ID
WHERE B.SALES_DATE LIKE '2022-01%'
GROUP BY CATEGORY
ORDER BY A.CATEGORY;